project_name: argocd-rbac-operator

builds:
  - id: rbac-operator
    main: ./cmd
    binary: rbac-operator
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/argoproj-labs/argocd-rbac-operator/version.Version={{ .Version }}
      - -extldflags="-static"
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: arm64

dockers:
  - image_templates:
      - quay.io/argoprojlabs/argocd-rbac-operator:v{{.Version}}
      - quay.io/argoprojlabs/argocd-rbac-operator:latest
    dockerfile: release.Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version=v{{.Version}}"
    - "--platform=linux/amd64"


archives:
  - format: tar.gz
    id: binary
    builds:
    - rbac-operator

release:
  prerelease: auto
  draft: false
  header: |
    ## argocd-rbac-operator
    {{ .Date }}

    ### Docker images

    - quay.io/argoprojlabs/argocd-rbac-operator:{{ .Tag }}
    - quay.io/argoprojlabs/argocd-rbac-operator:latest

  footer: |
    **Full Changelog**: https://github.com/argoproj-labs/argocd-rbac-operator/compare/{{ .PreviousTag }}...{{ .Tag }}
    <a href="https://argoproj.github.io/cd/"><img src="https://raw.githubusercontent.com/argoproj/argo-site/c42c87e68cea647eadc1564e9e264621442aa8cf/src/images/icon.png" width="25%" ></a>

changelog:
  use:
    github
  sort: asc
  abbrev: 0
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^.*?Bump(\([[:word:]]+\))?.+$'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
