# permissions for end users to edit argocdrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: argocdrolebinding-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - argocdrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - argocdrolebindings/status
  verbs:
  - get
