# This rule is not used by the project argocd-rbac-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over rbac-operator.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: argocdprojectrole-admin-role
rules:
- apiGroups:
  - rbac-operator
  resources:
  - argocdprojectroles
  verbs:
  - '*'
- apiGroups:
  - rbac-operator
  resources:
  - argocdprojectroles/status
  verbs:
  - get
