# permissions for end users to view argocdrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: argocdrolebinding-viewer-role
rules:
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdrolebindings/status
  verbs:
  - get
