apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  namespace: {{ .Values.argocd.namespace }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - {{ .Values.argocd.cmName }}
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
