apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: manager-rolebinding
  namespace: {{ .Values.argocd.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "argocd-rbac-operator.serviceAccountName" . }}
  namespace: {{ include "argocd-rbac-operator.namespace" . }}