apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
  {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: {{ include "argocd-rbac-operator.name" . }}
  namespace: {{ include "argocd-rbac-operator.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "argocd-rbac-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rbac-operator
      labels:
      {{- include "argocd-rbac-operator.labels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "argocd-rbac-operator.serviceAccountName" . }}
      containers:
        - args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --argocd-rbac-cm-name={{ .Values.argocd.cmName }}
          - --argocd-rbac-cm-namespace={{ .Values.argocd.namespace }}
          command:
          - /rbac-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          name: {{ .Chart.Name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.containerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
