apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: argocd-rbac-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-rbac-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "argocd-rbac-operator.serviceAccountName" . }}
  namespace: {{ include "argocd-rbac-operator.namespace" . }}