apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: argocd-rbac-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdrolebindings
  - argocdroles
  verbs:
  - '*'
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdrolebindings/finalizers
  - argocdrolebindings/status
  - argocdroles/finalizers
  verbs:
  - '*'
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdroles/status
  verbs:
  - '*'
