{{- if .Values.argocd.createNamespace -}}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
    {{- include "argocd-rbac-operator.selectorLabels" . | nindent 4 }}
  name: {{ include "argocd-rbac-operator.namespace" . }}
{{- end }}
