apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: {{ include "argocd-rbac-operator.serviceAccountName" . }}
  namespace: {{ include "argocd-rbac-operator.namespace" . }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}