---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: argocd-rbac-operator-argocdrolebinding-viewer-role
rules:
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdrolebindings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: argocd-rbac-operator-argocdrole-viewer-role
rules:
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdroles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: argocd-rbac-operator-argocdprojectrole-viewer-role
rules:
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdprojectroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdprojectroles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "argocd-rbac-operator.labels" . | nindent 4 }}
  name: argocd-rbac-operator-argocdprojectrolebinding-viewer-role
rules:
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdprojectrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-operator.argoproj-labs.io
  resources:
  - argocdprojectrolebindings/status
  verbs:
  - get
