apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-appproject-1
  labels:
    app.kubernetes.io/name: argocd-rbac-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  description: "Test AppProject 1 for ArgoCD's RBAC Operator"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-appproject-2
  labels:
    app.kubernetes.io/name: argocd-rbac-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  description: "Test AppProject 2 for ArgoCD's RBAC Operator"
