## Append samples of your project ##
resources:
- argocdrole.yaml
- argocdrolebinding.yaml
- rbac-operator_v1alpha1_argocdprojectrole.yaml
- rbac-operator_v1alpha1_argocdprojectrolebinding.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
